# Generated by Django 5.0.2 on 2024-07-11 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
