# Generated by Django 5.0.2 on 2024-07-06 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "goal",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Lose Weight", "Lose Weight"),
                            ("Maintain Weight", "Maintain Weight"),
                            ("Gain Weight", "Gain Weight"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("weight", models.FloatField(blank=True, null=True)),
                ("height", models.FloatField(blank=True, null=True)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("daily_calorie_goal", models.IntegerField(blank=True, null=True)),
                ("daily_protein_goal", models.IntegerField(blank=True, null=True)),
                ("daily_carb_goal", models.IntegerField(blank=True, null=True)),
                ("daily_fat_goal", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="WeightLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("weight", models.FloatField()),
            ],
        ),
    ]
