# Generated by Django 5.0.2 on 2024-07-10 01:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meal", "0002_auto_20240707_1901"),
    ]

    operations = [
        migrations.AddField(
            model_name="meal",
            name="total_calories",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="meal",
            name="total_carbs",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="meal",
            name="total_fats",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="meal",
            name="total_proteins",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
