# Generated by Django 5.0.2 on 2024-07-10 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meal", "0005_alter_mealitem_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="meal",
            name="meals",
        ),
        migrations.AddField(
            model_name="mealitem",
            name="meal_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="meal.meal",
            ),
        ),
    ]
