# Generated by Django 5.0.2 on 2024-07-10 18:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("meal", "0006_remove_meal_meals_mealitem_meal_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="meal",
            name="total_calories",
        ),
        migrations.RemoveField(
            model_name="meal",
            name="total_carbs",
        ),
        migrations.RemoveField(
            model_name="meal",
            name="total_fats",
        ),
        migrations.RemoveField(
            model_name="meal",
            name="total_proteins",
        ),
    ]
