# Generated by Django 5.0.2 on 2024-07-17 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0009_meal_meal_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompts',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prompts',
            name='input_tokens',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prompts',
            name='output_tokens',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
