# Generated by Django 5.0.2 on 2024-07-17 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0010_prompts_cost_prompts_input_tokens_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompts',
            name='cost',
            field=models.DecimalField(decimal_places=10, max_digits=10),
        ),
    ]
