# Generated by Django 5.0.2 on 2024-07-10 01:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_stat", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermetrics",
            name="activity_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Sedentary", "Sedentary"),
                    ("Lightly Active", "Lightly Active"),
                    ("Moderately Active", "Moderately Active"),
                    ("Very Active", "Very Active"),
                    ("Extra Active", "Extra Active"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="usermetrics",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="usermetrics",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("Male", "Male"), ("Female", "Female")],
                max_length=255,
                null=True,
            ),
        ),
    ]
