# Generated by Django 5.0.2 on 2024-07-07 00:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meal", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mealitem",
            name="servings",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="mealitem",
            name="calories",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="mealitem",
            name="carbs",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="mealitem",
            name="fats",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="mealitem",
            name="proteins",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
