# Generated by Django 5.0.2 on 2024-07-07 19:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("meal", "0001_initial"),
    ]

    operations = []
