# Generated by Django 5.0.2 on 2024-07-10 02:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meal", "0004_alter_mealitem_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mealitem",
            name="image",
            field=models.ImageField(
                blank=True, max_length=1000, null=True, upload_to="meal_items/"
            ),
        ),
    ]
