# Generated by Django 5.0.2 on 2024-07-10 20:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("meal", "0007_remove_meal_total_calories_remove_meal_total_carbs_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="meal",
            name="name",
        ),
    ]
