# Generated by Django 5.0.2 on 2024-07-10 23:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meal", "0008_remove_meal_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="meal",
            name="meal_date",
            field=models.DateField(
                auto_now_add=True, default=datetime.date(2024, 7, 10)
            ),
            preserve_default=False,
        ),
    ]
